<a href="https://colab.research.google.com/github/surajitaiml711-cloud/churn-analysis/blob/main/Churn_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
%matplotlib
import sqlite3

Using matplotlib backend: agg

In [ ]:


# Connect to SQLite database
conn = sqlite3.connect('/content/drive/MyDrive/Colab Notebooks/PYTHON_40/Churn Analysis/customer_churn.db')

# sql query to Get all table names
sql_query = """
        SELECT name
        FROM sqlite_master
        WHERE type='table';
"""
tables = pd.read_sql(sql_query, conn)

for table_name in tables['name']:
    df = pd.read_sql(f"SELECT * FROM {table_name}", conn)
    globals()[f"df_{table_name}"] = df
    print(f"Created dataframe: df_{table_name}")


conn.close()

Created dataframe: df_db_customer
Created dataframe: df_db_subscription
Created dataframe: df_db_support

In [ ]:
# Print table names and column names
conn = sqlite3.connect('/content/drive/MyDrive/Colab Notebooks/PYTHON_40/Churn Analysis/customer_churn.db')

for table_name in tables['name']:
    print(f"\nTable Name: {table_name}")
    # Get column information
    columns_query = f"PRAGMA table_info({table_name});"
    columns = pd.read_sql(columns_query, conn)
    print("Columns:")
    print(columns['name'].tolist())

# Close connection
conn.close()

Table Name: db_customer
Columns:
['customerid', 'name', 'country', 'state', 'gender', 'dob', 'interests', 'pincode']

Table Name: db_subscription
Columns:
['customerid', 'subscription_start_date', 'subscription_type', 'renewal_date', 'plan_type', 'contract_type', 'cancellation_date', 'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score']

Table Name: db_support
Columns:
['customerid', 'complaint_date', 'escalations', 'csat_score', 'col_1', 'comment']

# **Data cleaning**

In [ ]:
df_db_customer.tail()

,customerid,name,country,state,gender,dob,interests,pincode
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00,None,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00,None,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00,None,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00,None,None
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00,None,None

In [ ]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerid  21 non-null     object
 1   name        21 non-null     object
 2   country     18 non-null     object
 3   state       21 non-null     object
 4   gender      21 non-null     object
 5   dob         21 non-null     object
 6   interests   4 non-null      object
 7   pincode     0 non-null      object
dtypes: object(8)
memory usage: 1.4+ KB

In [ ]:
#rename col
df_db_customer.rename(columns = {'name' : 'customer_name'}, inplace= True)

In [ ]:
#drop col
df_db_customer.drop(columns=['interests', 'pincode'], inplace=True)

In [ ]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     object
 1   customer_name  21 non-null     object
 2   country        18 non-null     object
 3   state          21 non-null     object
 4   gender         21 non-null     object
 5   dob            21 non-null     object
dtypes: object(6)
memory usage: 1.1+ KB

In [ ]:
#change dataype
df_db_customer['dob'] = pd.to_datetime(df_db_customer['dob'])

In [ ]:
#d. Data standardization
df_db_customer['gender'] = df_db_customer['gender'].replace({'Men' : 'Male', 'Women' : 'Female'})
df_db_customer['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
df_db_customer[df_db_customer['country'].isna()]

    customerid customer_name country      state  gender        dob
5   0013-MHZWF         durga    None      Delhi  Female 1988-12-10
8   0015-UOCOJ          maya    None  Kathmandu  Female 1985-07-07
12  0018-NYROU        chitra    None  Telangana  Female 2004-12-01

In [ ]:

# Creating state → country map from non-null rows
state_country_mapping = df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()

# Fill the missing country using State
df_db_customer['country'] = df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))

In [ ]:
df_db_customer[df_db_customer['country'].isna()] # no null value in country col

Empty DataFrame
Columns: [customerid, customer_name, country, state, gender, dob]
Index: []

In [ ]:
df_db_subscription.head() # subcription table

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,None,None,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,None,None,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,None,None,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88

In [ ]:
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     object
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     object
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      object
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: float64(1), int64(2), object(8)
memory usage: 1.9+ KB

In [ ]:
# change data type to date - subscription_start_date , renewal_date, cancellation_date
date_col = ['subscription_start_date', 'renewal_date', 'cancellation_date']

df_db_subscription[date_col] = df_db_subscription[date_col].apply(pd.to_datetime)
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     datetime64[ns]
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     datetime64[ns]
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      datetime64[ns]
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[ns](3), float64(1), int64(2), object(5)
memory usage: 1.9+ KB

In [ ]:
df_db_support.head() # support table

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,None
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,None

In [ ]:
# drop columns
df_db_support.drop(columns=['col_1', 'comment'], inplace=True)

In [ ]:
# change data type to date - complaint_date

df_db_support['complaint_date'] = pd.to_datetime(df_db_support['complaint_date'])
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      datetime64[ns]
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 420.0+ bytes

## 3. Feature Engineering & Data Analysis

In [ ]:
# create a new col using existing col - churn flag

# Customer is churned if cancellation_date is not null
df_db_subscription['churn_flag'] = np.where(df_db_subscription['cancellation_date'].notna(), 1, 0)
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score,churn_flag
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,None,13.99,627,12,0
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,None,6.99,210,34,0
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,None,22.99,1725,8,0
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88,1

In [ ]:
# first fix support table duplicates then merge
# Note: while merging df's always check the shape before and after
df = (df_db_subscription
            .merge(df_db_customer, on = 'customerid', how= 'left')
            .merge(df_db_support, on = 'customerid', how= 'left') )

In [ ]:
df_db_subscription.shape

(21, 12)

In [ ]:
df.shape

(23, 20)

In [ ]:
print('df_db_subscription unique value:', df_db_subscription['customerid'].nunique())
print('df_db_customer unique value:', df_db_customer['customerid'].nunique())
print('df_db_support unique value:', df_db_support['customerid'].nunique())
print('df_db_support all value:', df_db_support['customerid'].size)

df_db_subscription unique value: 21
df_db_customer unique value: 21
df_db_support unique value: 7
df_db_support all value: 9

In [ ]:
df_db_support

   customerid complaint_date escalations  csat_score
0  0003-MKNFE     2024-08-28           N          60
1  0003-MKNFE     2024-08-28           Y          10
2  0013-EXCHZ     2024-01-20           Y          20
3  0013-MHZWF     2025-03-18           N          90
4  0013-SMEOE     2024-11-01           N          30
5  0017-IUDMW     2024-04-10           Y          25
6  0019-EFAEP     2024-09-27           Y          30
7  0022-TCJCI     2024-09-13           Y          10
8  0022-TCJCI     2024-09-14           N          90

In [ ]:
df_db_support['complaint_count'] = df_db_support.groupby('customerid')['customerid'].transform('count')

In [ ]:
df_db_support = df_db_support.sort_values('complaint_date').drop_duplicates('customerid', keep= 'last')

In [ ]:
# merge df
df = (df_db_subscription
            .merge(df_db_customer, on = 'customerid', how= 'left')
            .merge(df_db_support, on = 'customerid', how= 'left') )

In [ ]:
df.shape

(21, 21)

In [ ]:
# export dataframe to csv file
df.to_csv('exported_churn_data.csv', index=False)

**Data Analysis**

In [ ]:
# 1. Churn Rate
churn_rate = df['churn_flag'].mean()*100
print("Churn Rate = ", round(churn_rate,2), "%")

Churn Rate =  28.57 %

In [ ]:
# 2. Retenion Rate
retention_rate = 100 - churn_rate
print("Retention Rate = ", round(retention_rate,2), "%")

Retention Rate =  71.43 %

In [ ]:
# 3. Churn by Plan type
churn_by_plan = (df.groupby('plan_type')['churn_flag'].mean().mul(100).round(2).reset_index(name='churn_rate_pct'))
print(churn_by_plan)

  plan_type  churn_rate_pct
0     Basic           60.00
1   Premium           14.29
2  Standard           22.22

In [ ]:
# 4 a. Churn by state + sum(revenue) & count of users  -- home work **
# 4 b. Churn by subscription type + sum(revenue) & count of users   -- home work **

In [ ]:
print("\n--- 4 a. Churn by state + sum(revenue) & count of users ---")
churn_by_state = df.groupby('state').agg(
    churn_rate_pct=('churn_flag', lambda x: x.mean() * 100),
    total_revenue=('monthly_charges', 'sum'),
    user_count=('customerid', 'nunique')
).round(2).reset_index()
print(churn_by_state)

print("\n--- 4 b. Churn by subscription type + sum(revenue) & count of users ---")
churn_by_subscription_type = df.groupby('subscription_type').agg(
    churn_rate_pct=('churn_flag', lambda x: x.mean() * 100),
    total_revenue=('monthly_charges', 'sum'),
    user_count=('customerid', 'nunique')
).round(2).reset_index()
print(churn_by_subscription_type)

--- 4 a. Churn by state + sum(revenue) & count of users ---
           state  churn_rate_pct  total_revenue  user_count
0          Delhi           25.00          52.96           4
1      Karnataka          100.00          20.98           2
2      Kathmandu            0.00          20.98           2
3    Maharashtra            0.00          50.97           3
4      Meghalaya           66.67          42.97           3
5       Nagaland            0.00          22.99           1
6      Rajasthan            0.00          36.98           2
7      Telangana           50.00          30.98           2
8  Uttar Pradesh            0.00         115.98           2

--- 4 b. Churn by subscription type + sum(revenue) & count of users ---
  subscription_type  churn_rate_pct  total_revenue  user_count
0           Organic            0.00         145.91           9
1              Paid           16.67         174.94           6
2          Refferal           83.33          74.94           6

In [ ]:
# 5. ARPU - Avg Revenue per user
arpu = df['monthly_charges'].mean()
print('ARPU = ', round(arpu,2))

ARPU =  18.85

In [ ]:
# homework - calculate customer age
import datetime

# Calculate customer age
df['customer_age'] = (pd.Timestamp.now().year - df['dob'].dt.year)

# Display first few rows with the new 'customer_age' column
print(df[['customerid', 'dob', 'customer_age']].head())

   customerid        dob  customer_age
0  0002-ORFBO 1982-04-12            44
1  0003-MKNFE 1995-11-23            31
2  0004-TLHLJ 1978-02-15            48
3  0011-IGKFF 2001-08-30            25
4  0013-EXCHZ 1990-05-05            36

In [ ]:
# 6. Avg Customer Tenure
# count of days users has used our service : cancellation date else current date
today = pd.Timestamp.today()

df['tenure_days'] = np.where(
        df['cancellation_date'].notna(),

    (df['cancellation_date'] - df['subscription_start_date']).dt.days,

    (today - df['subscription_start_date']).dt.days
)

avg_tenure = df['tenure_days'].mean()
print("Avg Tenure (Days) = ", round(avg_tenure),0)

Avg Tenure (Days) =  1539 0

In [ ]:
# 7. Revenue at risk - revenue lost from churned users
revenue_at_risk = df.loc[df['churn_flag']==1, 'monthly_charges'].sum()
print("Revenue at Risk (Rs 'K') =", revenue_at_risk)

Revenue at Risk (Rs 'K') = 73.94

In [ ]:
# 8. Esclation Rate
escalation_rate = (df['escalations']=='Y').mean()*100
print("Esclation Rate = ", round(escalation_rate, 2), "%")

Esclation Rate =  19.05 %

In [ ]:
# 9. Avg Complaint Per User
avg_complaints = df['complaint_count'].sum() / df['customerid'].nunique()
print("Avg Compliants Per User = ", round(avg_complaints, 2))

Avg Compliants Per User =  0.43

In [ ]:
# 10. Correlation Esclation vs Churn
df['escalations'] = np.where(df['escalations'] == 'Y', 1, 0) # encoding string to int type
corr_df = df[['escalations', 'churn_flag']].dropna()

correlation = corr_df['escalations'].corr(df['churn_flag'])
print("Correlation between esclation vs churn is = ", round(correlation,2))

Correlation between esclation vs churn is =  0.77

## 4. Visualization using Matplotlib

In [ ]:
# best practice to create a copy then work on it
df_visual = df.copy()

In [ ]:
df_visual.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score',
       'churn_flag', 'customer_name', 'country', 'state', 'gender', 'dob',
       'complaint_date', 'escalations', 'csat_score', 'complaint_count',
       'customer_age', 'tenure_days'],
      dtype='object')

In [ ]:


df_visual['cancellation_month'] = (
    df_visual['cancellation_date'].dt.to_period('M').astype(str)
)

churn_trend = (
    df_visual[df_visual['churn_flag'] == 1]
    .groupby('cancellation_month')
    .size()
    .reset_index(name='churned_customers')
)

fig = px.line(
    churn_trend,
    x='cancellation_month',
    y='churned_customers',
    markers=True,
    title='Monthly Churn Trend',
    labels={
        'cancellation_month': 'Month',
        'churned_customers': 'Churned Customers'
    }
)

fig.update_traces(
    line=dict(dash='dash', width=2),
    marker=dict(size=10)
)

fig.update_layout(
    width=800,
    height=300
)

fig.show()

In [ ]:


# Calculate churn rate by plan type
churn_plan = (
    df_visual.groupby('plan_type')['churn_flag']
    .mean()
    .reset_index()
)

# Convert churn rate to percentage
churn_plan['churn_rate'] = churn_plan['churn_flag'] * 100

# Create bar chart
fig = px.bar(
    churn_plan,
    x='plan_type',
    y='churn_rate',
    title='Churn Rate by Plan Type',
    labels={
        'plan_type': 'Plan Type',
        'churn_rate': 'Churn Rate (%)'
    },
    text='churn_rate',
    color='plan_type',
    color_discrete_sequence=['yellow', 'purple', 'blue']
)

fig.update_traces(
    texttemplate='%{text:.1f}%',
    textposition='outside'
)

fig.update_layout(
    width=700,
    height=400
)

fig.show()

In [ ]:

# Calculate churn rate by state
churn_state = (
    df_visual.groupby('state')['churn_flag']
    .mean()
    .reset_index()
)

# Convert churn rate to percentage
churn_state['churn_rate'] = churn_state['churn_flag'] * 100

# Create bar chart
fig = px.bar(
    churn_state,
    x='state',
    y='churn_rate',
    title='Churn Rate by State',
    labels={
        'state': 'State',
        'churn_rate': 'Churn Rate (%)'
    },
    text='churn_rate'
)

# Format percentage labels
fig.update_traces(
    texttemplate='%{text:.1f}%',
    textposition='outside'
)

# Rotate state names
fig.update_layout(
    width=1200,
    height=400,
    xaxis_tickangle=-45
)

fig.show()

#  Visulaization using Seaborn

In [ ]:
# Heatmap (Correlation Matrix)

In [ ]:
# encoding - convert str to numeric so that we can find corr between features
df_visual.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score',
       'churn_flag', 'customer_name', 'country', 'state', 'gender', 'dob',
       'complaint_date', 'escalations', 'csat_score', 'complaint_count',
       'customer_age', 'tenure_days', 'cancellation_month'],
      dtype='object')

In [ ]:
df_visual[['plan_type', 'contract_type', 'churn_score', 'churn_flag', 'escalations']].head()

  plan_type contract_type  churn_score  churn_flag  escalations
0  Standard        Annual           12           0            0
1   Premium        Annual           91           1            1
2     Basic       Monthly           34           0            0
3   Premium        Annual            8           0            0
4  Standard       Monthly           88           1            1

In [ ]:
# incorrect method of encoding - as numbers are not assigned based on priority
df_encoded = df_visual[['plan_type', 'contract_type', 'churn_score', 'churn_flag', 'escalations']].copy()

categorial_cols = ['plan_type', 'contract_type']

for col in categorial_cols:
    df_encoded[col] = df_encoded[col].astype('category').cat.codes

In [ ]:



# Calculate correlation matrix
corr_matrix = df_encoded.corr()

# Create heatmap
fig = px.imshow(
    corr_matrix,
    text_auto=True,
    title='Correlation Heatmap',
    color_continuous_scale='RdBu_r',
    zmin=-1,
    zmax=1
)

fig.update_layout(
    width=800,
    height=700
)

fig.show()

In [ ]:
print('plan_type :', df_visual['plan_type'].unique())
print('contract_type :', df_visual['contract_type'].unique())

plan_type : ['Standard' 'Premium' 'Basic']
contract_type : ['Annual' 'Monthly']

In [ ]:
# Correct method of encoding - based on priority
df_encoded = df_visual[['plan_type', 'contract_type', 'churn_score', 'churn_flag', 'escalations']].copy()

order_mappings = {
    'plan_type' : ['Basic', 'Standard', 'Premium'],
    'contract_type' : ['Monthly', 'Annual']
    }

for col, order in order_mappings.items():
    df_encoded[col] = pd.Categorical(df_encoded[col].astype('category'), categories=order, ordered=True).codes

In [ ]:
df_visual[['plan_type', 'contract_type', 'churn_score', 'churn_flag', 'escalations']].head()

  plan_type contract_type  churn_score  churn_flag  escalations
0  Standard        Annual           12           0            0
1   Premium        Annual           91           1            1
2     Basic       Monthly           34           0            0
3   Premium        Annual            8           0            0
4  Standard       Monthly           88           1            1

In [ ]:
df_encoded.head()

   plan_type  contract_type  churn_score  churn_flag  escalations
0          1              1           12           0            0
1          2              1           91           1            1
2          0              0           34           0            0
3          2              1            8           0            0
4          1              0           88           1            1

In [ ]:
corr_matrix = df_encoded.corr()

fig = px.imshow(
    corr_matrix,
    text_auto=True,
    title='Correlation Matrix',
    color_continuous_scale='RdBu_r',
    zmin=-1,
    zmax=1
)

fig.show()

In [ ]:


# Correlation matrix
corr_matrix = df_encoded.corr()

# Create heatmap
fig = px.imshow(
    corr_matrix,
    text_auto='.2f',
    color_continuous_scale='RdBu_r', # Changed from 'coolwarm' to 'RdBu_r'
    zmin=-1,
    zmax=1,
    title='Correlation Heatmap'
)

# Rotate x-axis labels
fig.update_xaxes(tickangle=45)

# Figure size
fig.update_layout(
    width=1000,
    height=600
)

fig.show()

In [ ]:
# pairplot - Plot pairwise relationships in a dataset
sns.pairplot(df_encoded)

In [ ]:
df_visual.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score',
       'churn_flag', 'customer_name', 'country', 'state', 'gender', 'dob',
       'complaint_date', 'escalations', 'csat_score', 'complaint_count',
       'customer_age', 'tenure_days', 'cancellation_month'],
      dtype='object')

In [ ]:
# catplt/Facegrid plot - multi-dim comparison
g = sns.catplot(
    data=df_visual,
    x='plan_type',
    y='monthly_charges',
    hue='gender',
    col='churn_flag',
    kind='bar',
    height=4,
    aspect=1.2
)


plt.show()

In [ ]:
# Pivot Table

pd.pivot_table(
    df_visual,
    index='plan_type',
    values='churn_flag',
    aggfunc = 'mean'
)

           churn_flag
plan_type
Basic        0.600000
Premium      0.142857
Standard     0.222222

In [ ]:
# pivot table using multiple cols and agg type

pd.pivot_table(
    df_visual,
    index='plan_type',
    values=['monthly_charges', 'customerid', 'churn_flag'],
    aggfunc = {
        'monthly_charges' : 'sum',
        'customerid' : 'nunique',
        'churn_flag' : 'mean'
    }
)

           churn_flag  customerid  monthly_charges
plan_type
Basic        0.600000           5            52.95
Premium      0.142857           7           218.93
Standard     0.222222           9           123.91

Project Completed :

In [ ]:
# import os

# os.remove("test_database.sqlite")

# print("Database deleted!")

In [ ]:
conn = sqlite3.connect('test_database.sqlite')

#table details
conn.execute("CREATE TABLE IF NOT EXISTS users (first_name TEXT, country TEXT, budget INTEGER)")

# commit and save
conn.commit()

print("Cretaed Table successfully!")

Cretaed Table successfully!

In [ ]:
# insert data

cursor = conn.cursor()

# write sql query to insert records in sql table
cursor.execute(
    """
        INSERT INTO users VALUES
            ('Madhav', 'India', 5000),
            ('Rishabh', 'Germany', 2500),
            ('Vishakha', 'India', 3500)
    """
)

# commit and save
conn.commit()

print("Data Inserted successfully!")

Data Inserted successfully!

In [ ]:
# check inserted data in table
conn = sqlite3.connect('test_database.sqlite')
query = """SELECT * FROM users"""

df_results = pd.read_sql(query, conn)

df_results.head()

  first_name  country  budget
0     Madhav    India    5000
1    Rishabh  Germany    2500
2   Vishakha    India    3500

In [ ]:
# aggregation
query = """
        SELECT country, SUM(budget) as total_budget
        FROM users
        GROUP BY country
"""
df_agg = pd.read_sql(query, conn)
df_agg

   country  total_budget
0  Germany          2500
1    India          8500

In [ ]:
conn.close()